-- Start of AF tables --
CREATE TABLE IF NOT EXISTS AF_APPLICATION (
	ID INTEGER AUTO_INCREMENT,
	APPLICATION_KEY VARCHAR(100) NOT NULL,
	APPLICATION_NAME VARCHAR(250) NOT NULL,
	TENANT_ID INTEGER NOT NULL,
	STATUS VARCHAR(100) NOT NULL DEFAULT 'PENDING',
	PRIMARY KEY(ID),
	UNIQUE (APPLICATION_KEY,TENANT_ID)
);

CREATE TABLE IF NOT EXISTS AF_VERSION (
	ID INTEGER AUTO_INCREMENT,
	APPLICATION_ID INTEGER NOT NULL,
	VERSION_NAME VARCHAR(100) NOT NULL,
	STAGE VARCHAR(100) DEFAULT 'Development',
	PROMOTE_STATUS VARCHAR(100) NULL,
	FOREIGN KEY(APPLICATION_ID) REFERENCES AF_APPLICATION(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY(ID),
        UNIQUE (VERSION_NAME,APPLICATION_ID)
);

CREATE TABLE IF NOT EXISTS AF_REPOSITORY (
	    ID INTEGER AUTO_INCREMENT,
        VERSION_ID INTEGER NOT NULL,
        REPOSITORY_IS_FORK TINYINT DEFAULT 0,
	    USER_ID VARCHAR(100) NULL,
        FOREIGN KEY(VERSION_ID) REFERENCES AF_VERSION(ID) ON UPDATE CASCADE ON
        DELETE RESTRICT,
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS AF_BUILD (
        ID INTEGER AUTO_INCREMENT,
        REPOSITORY_ID INTEGER NOT NULL,
        CURRENT_BUILD VARCHAR(100) NULL,
        LAST_BUILD VARCHAR(100) NULL,
        LAST_BUILD_STATUS VARCHAR(100) NULL,
        LAST_BUILD_TIME TIMESTAMP NULL,
        FOREIGN KEY(REPOSITORY_ID) REFERENCES AF_REPOSITORY(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS AF_DEPLOY (
        ID INTEGER AUTO_INCREMENT,
        REPOSITORY_ID INTEGER NOT NULL,
        LAST_DEPLOY VARCHAR(100) NULL,
        LAST_DEPLOY_STATUS VARCHAR(100) NULL,
        LAST_DEPLOY_TIME TIMESTAMP NULL,
        ENVIRONMENT VARCHAR(100) NULL,
        FOREIGN KEY(REPOSITORY_ID) REFERENCES AF_REPOSITORY(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS AF_RESOURCE (
        ID INTEGER AUTO_INCREMENT,
        APPLICATION_ID INTEGER NOT NULL,
        RESOURCE_TYPE VARCHAR(100) NOT NULL,
        RESOURCE_NAME VARCHAR(100) NOT NULL,
        ENVIRONMENT VARCHAR(100) NOT NULL,
        DESCRIPTION VARCHAR(2000) NOT NULL,
        FOREIGN KEY(APPLICATION_ID) REFERENCES AF_APPLICATION(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS AF_CARTRIDGE_CLUSTER (
  ID INTEGER AUTO_INCREMENT,
  CLUSTER_ID VARCHAR(100) NOT NULL,
  LB_CLUSTER_ID VARCHAR(100),
  ACTIVE_IP VARCHAR(100) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE(CLUSTER_ID)
);
-- End of AF tables --

