/*
 * Copyright 2005-2011 WSO2, Inc. (http://wso2.com)
 *
 *      Licensed under the Apache License, Version 2.0 (the "License");
 *      you may not use this file except in compliance with the License.
 *      You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *      Unless required by applicable law or agreed to in writing, software
 *      distributed under the License is distributed on an "AS IS" BASIS,
 *      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *      See the License for the specific language governing permissions and
 *      limitations under the License.
 */

package org.wso2.carbon.appfactory.application.mgt.type;

import org.apache.axiom.om.OMElement;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.wso2.carbon.appfactory.common.AppFactoryConfiguration;
import org.wso2.carbon.appfactory.common.AppFactoryConstants;
import org.wso2.carbon.appfactory.common.AppFactoryException;
import org.wso2.carbon.appfactory.common.util.AppFactoryUtil;
import org.wso2.carbon.appfactory.core.apptype.ApplicationTypeManager;
import org.wso2.carbon.appfactory.core.dao.JDBCApplicationDAO;
import org.wso2.carbon.appfactory.core.dto.CartridgeCluster;
import org.wso2.carbon.appfactory.core.util.AppFactoryCoreUtil;
import org.wso2.carbon.appfactory.s4.integration.StratosRestService;
import org.wso2.carbon.appfactory.utilities.project.ProjectUtils;
import org.wso2.carbon.appfactory.utilities.version.AppVersionStrategyExecutor;
import org.wso2.carbon.context.CarbonContext;

import java.io.File;
import java.util.Map;

/**
 * PHP application type processor
 */
public class PHPApplicationTypeProcessor extends AbstractApplicationTypeProcessor {
    private static final Log log = LogFactory.getLog(PHPApplicationTypeProcessor.class);
    private static final String PARAM_CARTRIDGE_IP = "{cartridgeIP}";
    private static final String ENVIRONMENT = "ApplicationDeployment.DeploymentStage";
    private static final String TENANT_MANAGEMENT_URL = "TenantMgtUrl";
    private static final String SYMBOL_AT = "@";

    @Override
    public void doVersion(String applicationId, String targetVersion, String currentVersion, String workingDirectory)
		    throws AppFactoryException {
        AppVersionStrategyExecutor.doVersionForGenericApplicationType(targetVersion, new File(workingDirectory));
    }

    @Override
    public void generateApplicationSkeleton(String applicationId, String workingDirectory) throws AppFactoryException {
	    ProjectUtils.generateProjectArchetype(applicationId, workingDirectory,
	                                          ProjectUtils.getArchetypeRequest(applicationId,
	                                                                           getProperty(MAVEN_ARCHETYPE_REQUEST)));
	    //delete pom.xm generated by maven archetype
	    File pomFile = new File(workingDirectory + File.separator + AppFactoryConstants.DEFAULT_POM_FILE);
	    boolean result = FileUtils.deleteQuietly(pomFile);
	    if (!result){
		    log.warn("Error while deleting pom.xml for application id : " + applicationId);
	    }
    }

    @Override
    public String getDeployedURL(String tenantDomain, String applicationId, String applicationVersion, String stage)
            throws AppFactoryException {

        String deployedUrl = StringUtils.EMPTY;
        try {
            String urlPattern = (String) this.properties.get(LAUNCH_URL_PATTERN);
            String artifactTrunkVersionName = AppFactoryUtil.getAppfactoryConfiguration().
                    getFirstProperty(ARTIFACT_VERSION_XPATH);
            String sourceTrunkVersionName = AppFactoryUtil.getAppfactoryConfiguration().
                    getFirstProperty(SOURCE_VERSION_XPATH);

            if (sourceTrunkVersionName.equalsIgnoreCase(applicationVersion)) {
                applicationVersion = artifactTrunkVersionName;
            }

            // get cartridge active IP
            String cartridgeActiveIp = getCartridgeActiveIP(applicationId, tenantDomain, stage);

            // generate application url
            if (StringUtils.isNotBlank(urlPattern) && StringUtils.isNotBlank(cartridgeActiveIp)) {
                urlPattern = urlPattern.replace(PARAM_CARTRIDGE_IP, cartridgeActiveIp)
                        .replace(PARAM_APP_ID, applicationId)
                        .replace(PARAM_APP_VERSION, applicationVersion);
                deployedUrl = urlPattern;
            }
        } catch (AppFactoryException e) {
            if (log.isErrorEnabled()) {
                log.error("Error while generating application url !", e);
            }
        }
        return deployedUrl;

    }

    @Override
    public OMElement configureBuildJob(OMElement jobConfigTemplate, Map<String, String> parameters,
                                       String projectType) throws AppFactoryException {
        if (jobConfigTemplate == null) {
            String msg =
                    "Class loader is unable to find the jenkins job configuration template for uploadable application types";
            log.error(msg);
            throw new AppFactoryException(msg);
        }

        String artifactArchiver = null;
        Object hudsonArtifactArchiver = ApplicationTypeManager.getInstance().getApplicationTypeBean(projectType)
                                                              .getProperty(
                                                                      AppFactoryConstants.HUDSON_ARTIFACT_ARCHIVER);
        if (hudsonArtifactArchiver != null) {
            artifactArchiver = hudsonArtifactArchiver.toString();
        }
        jobConfigTemplate = configureRepositoryData(jobConfigTemplate, parameters);

        // Support for post build listener residing in jenkins server
        setValueUsingXpath(jobConfigTemplate,
                           AppFactoryConstants.PUBLISHERS_APPFACTORY_POST_BUILD_APP_EXTENSION_XPATH_SELECTOR,
                           parameters.get(AppFactoryConstants.APPTYPE_EXTENSION));

        setValueUsingXpath(jobConfigTemplate,
                           AppFactoryConstants.PUBLISHERS_APPFACTORY_POST_BUILD_APP_ID_XPATH_SELECTOR,
                           parameters.get(AppFactoryConstants.APPLICATION_ID));

        setValueUsingXpath(jobConfigTemplate,
                           AppFactoryConstants.PUBLISHERS_APPFACTORY_POST_BUILD_APP_VERSION_XPATH_SELECTOR,
                           parameters.get(AppFactoryConstants.APPLICATION_VERSION));

        if (StringUtils.isNotBlank(artifactArchiver)) {
            setValueUsingXpath(jobConfigTemplate,
                               AppFactoryConstants.ARTIFACT_ARCHIVER_CONFIG_NAME_XAPTH_SELECTOR,
                               artifactArchiver);
        }

        if (ApplicationTypeManager.getInstance().getApplicationTypeBean(projectType).isUploadableAppType()) {
            setValueUsingXpath(jobConfigTemplate, AppFactoryConstants.ARTIFACT_ARCHIVER_CONFIG_NAME_XAPTH_SELECTOR,
                               AppFactoryConstants.DEFAULT_ARTIFACT_NAME +
                               ApplicationTypeManager.getInstance().getApplicationTypeBean(projectType)
                                                     .getExtension());

            String repositoryBranchName = parameters.get(AppFactoryConstants.APPLICATION_VERSION);
            if (AppFactoryConstants.INITIAL_UPLOADED_APP_VERSION.equals(repositoryBranchName)) {
                setValueUsingXpath(jobConfigTemplate, AppFactoryConstants.GIT_REPOSITORY_VERSION_XPATH_SELECTOR,
                                   AppFactoryConstants.APPLICATION_VERSION_VALUE_FREESTYLE);
            }
        }

        setValueUsingXpath(jobConfigTemplate,
                           AppFactoryConstants.APPLICATION_TRIGGER_PERIOD,
                           parameters.get(AppFactoryConstants.APPLICATION_POLLING_PERIOD));

        return jobConfigTemplate;
    }

    private String getCartridgeActiveIP(String applicationId, String tenantDomain, String stage)
            throws AppFactoryException {
        AppFactoryConfiguration configuration = AppFactoryUtil.getAppfactoryConfiguration();
        String serverURL = configuration.getFirstProperty(ENVIRONMENT + XPATH_SEPERATOR + stage + XPATH_SEPERATOR +
                TENANT_MANAGEMENT_URL);
        String userName = CarbonContext.getThreadLocalCarbonContext().getUsername() + SYMBOL_AT +
                CarbonContext.getThreadLocalCarbonContext().getTenantDomain();
        String cartridgeAlias = AppFactoryCoreUtil.getCartridgeAlias(applicationId, tenantDomain);

        StratosRestService restService = new StratosRestService(serverURL, userName, StringUtils.EMPTY);
        String clusterId = restService.getSubscribedCartridgeClusterId(cartridgeAlias);

        // get data from runtime db
        JDBCApplicationDAO jdbcApplicationDAO = JDBCApplicationDAO.getInstance();
        CartridgeCluster cartridgeCluster = jdbcApplicationDAO.getCartridgeClusterByClusterId(clusterId);
        if(cartridgeCluster != null) {
            return cartridgeCluster.getActiveIP();
        }
        return null;
    }

}
